title: "Threat Lines"
description: "More Than Headlines. It's Threat Lines"
baseurl: "/threatlines"
url: "https://ronnie-bailey.github.io"

author: 
  name: "Ronnie Bailey" 
  title: "Cybersecurity Architect & Policy Advisor"
  bio: "10+ years securing enterprise systems while advising policymakers on technical implementations. Currently focused on AI governance and cloud identity management."
  credentials: ["CISSP", "CIPP/E"]

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ronnie Bailey"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

include: [assets]
